= TypesScript and CoffeeScript ports of the Meteor Leaderboard

:listingblock.: <pre><code>|</code></pre>

== TypesScript and CoffeeScript ports of the Meteor Leaderboard

Current version tested using:

- Meteor version 0.5.9
- Meteorite version 0.4.9
- TypeScript 0.8.3.0
- CoffeeScript version 1.6.2
- Jake 0.5.10

A http://www.typescriptlang.org/[TypeScript] port and a
http://coffeescript.org/[CoffeeScript] port of the
http://meteor.com/[Meteor] framework's
http://meteor.com/examples/leaderboard[Leaderboard example].  CSS
written using http://lesscss.org/[Less]. The UI uses Twitter
http://twitter.github.com/bootstrap/[Bootstrap] and
http://bootboxjs.com/[Bootbox.js].

The ports have been enhanced with:

- Bootstrap styling.
- Drop-down menus to reset the data and sort players by name and score.
- Tooltips.
- You can add and delete players.
- Login authentication.

Here's a
https://github.com/srackham/leaderboard/blob/master/screenshot.png[screenshot].


=== Installation
In addition to using built-in Meteor packages the project uses two
https://github.com/oortcloud/meteorite[Meteorite] smart packages:
'bootboxjs' for modal dialogs and 'toastjs' for popup notifications.

To create and install this meteor project you have to manually copy
the cloned Git repo to the to the Meteor project directory because Git
will not clone to an empty directory.

  mrt create meteorite-leaderboard
  # Replace default Meteorite project files with Leaderboard project files.
  rm meteorite-leaderboard/meteorite-leaderboard.*
  git clone git://github.com/srackham/leaderboard.git leaderboard.tmp
  mv leaderboard.tmp/* leaderboard.tmp/.git meteorite-leaderboard
  rm -rf leaderboard.tmp
  # Add Meteor packages.
  cd meteorite-leaderboard
  meteor remove insecure autopublish
  meteor add jquery bootstrap accounts-ui accounts-password accounts-google
  # Add Meteorite packages.
  mrt add bootboxjs
  mrt add toastjs
  # Build project.
  jake build.ts
  # Run project.
  mrt

The build process is managed by https://github.com/mde/jake[jake].
Run `jake build.ts` to compile the TypeScript port or `jake
build.cs` to compile the CoffeeScript port (choose one):

  jake build.ts   # TypeScript
  jake build.cs   # CoffeeScript

To start the project in the built-in Meteor server:

  meteor run

